'use client';
import { useEffect, useState } from 'react';
import { SCOPES as defaultScopes } from '@/lib/feishu-core';
import { Link2, ShieldCheck, FileSearch, FileText, Check, Copy, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
type AuthorizationProfile='read'|'documents_write'|'bitable_write';
type Connection={requires_attention:boolean;connection_issue:string|null;configured:boolean;connected:boolean;app_id:string|null;feishu_name:string|null;callback_url:string;scopes:string[]|null;authorization_request_scopes:string[];authorization_profiles:Record<AuthorizationProfile,{label:string;scopes:string[]}>;connect_url:string};

export default function Home(){
  const [connection,setConnection]=useState<Connection|null>(null);
  const [message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [needsLogin,setNeedsLogin]=useState(false),[appId,setAppId]=useState(''),[appSecret,setAppSecret]=useState('');
  const [edit,setEdit]=useState(false),[copied,setCopied]=useState('');
  const [profiles,setProfiles]=useState<AuthorizationProfile[]>(['read']),[extraScopes,setExtraScopes]=useState('');
  const [toolQuery,setToolQuery]=useState(''),[toolResult,setToolResult]=useState('');
  const [query,setQuery]=useState(''),[reference,setReference]=useState(''),[testResult,setTestResult]=useState('');
  const load=async()=>{setLoading(true);try{const r=await fetch('/api/connection',{cache:'no-store'});const d=await r.json() as Connection & {message?:string;url:string;error?:{message:string};result?:{isError?:boolean;content?:{text:string}[];structuredContent?:unknown}};if(!r.ok){setNeedsLogin(r.status===401);throw new Error(d.message||'读取连接状态失败。');}setConnection(d);setNeedsLogin(false);setAppId(d.app_id||'');}catch(e){setMessage((e as Error).message);}finally{setLoading(false);}};
  useEffect(()=>{void load();const p=new URLSearchParams(window.location.search);if(p.get('result')==='connected')setMessage('飞书授权已保存。现在可以验证文档读取，或从插件中使用。');if(p.get('result')==='error')setMessage(p.get('reason')||'授权未完成，请重试。');if(p.has('result'))window.history.replaceState({},'',window.location.pathname);},[]);
  const copy=async(value:string,id:string)=>{try{await navigator.clipboard.writeText(value);setCopied(id);setTimeout(()=>setCopied(''),1800);}catch{setMessage('复制失败，请选中文本手动复制。');}};
  const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'configure',app_id:appId,app_secret:appSecret})});const d=await r.json() as Connection & {message?:string;url:string;error?:{message:string};result?:{isError?:boolean;content?:{text:string}[];structuredContent?:unknown}};if(!r.ok)throw new Error(d.message||'保存失败。');setAppSecret('');setEdit(false);await load();setMessage('应用凭据已保存，请继续授权飞书。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const connect=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'authorize',profiles,extra_scopes:extraScopes.split(/[\s,]+/).filter(Boolean)})});const d=await r.json() as Connection & {message?:string;url:string;error?:{message:string};result?:{isError?:boolean;content?:{text:string}[];structuredContent?:unknown}};if(!r.ok)throw new Error(d.message||'无法开始授权。');window.location.assign(d.url);}catch(e){setMessage((e as Error).message);setBusy(false);}};
  const test=async(name:string,args:unknown)=>{setBusy(true);setTestResult('');try{const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});const d=await r.json() as Connection & {message?:string;url:string;error?:{message:string};result?:{isError?:boolean;content?:{text:string}[];structuredContent?:unknown}};if(d.error)throw new Error(d.error.message);const result=d.result;if(result?.isError)throw new Error(result.content?.[0]?.text||'验证失败。');setTestResult(JSON.stringify(result?.structuredContent,null,2));}catch(e){setTestResult((e as Error).message);}finally{setBusy(false);}};
  const removeConnection=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'disconnect'})});if(!r.ok)throw new Error('清除连接失败。');await load();setMessage('此服务中的应用凭据和授权记录已清除。飞书端可在应用授权管理中撤销授权。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const verifyWrite=async()=>{
    setBusy(true);setTestResult('');let documentId='';
    const call=async(name:string,args:unknown,write:boolean)=>{const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:write?'feishu_call_write_tool':'feishu_call_read_tool',arguments:{name,arguments:args}}})});const d=await r.json() as {error?:{message:string};result?:{isError?:boolean;content?:{text:string}[];structuredContent?:Record<string,unknown>}};if(!r.ok||d.error||d.result?.isError)throw new Error(d.error?.message||d.result?.content?.[0]?.text||'调用失败');return d.result?.structuredContent||{};};
    try{
      const created=await call('docx.v1.document.create',{data:{title:'飞书连接验证文档（可删除）'}},true);
      documentId=(created.document as {document_id:string}).document_id;
      const added=await call('docx.v1.documentBlockChildren.create',{path:{document_id:documentId,block_id:documentId},data:{children:[{block_type:2,text:{elements:[{text_run:{content:'插件写入测试'}}]}}],index:-1}},true);
      const blockId=(added.children as {block_id:string}[])[0].block_id;
      await call('docx.v1.documentBlock.patch',{path:{document_id:documentId,block_id:blockId},data:{update_text_elements:{elements:[{text_run:{content:'插件创建、追加、编辑和读取验证成功。'}}]}}},true);
      const read=await call('docx.v1.document.rawContent',{path:{document_id:documentId}},false);
      if(!String(read.content).includes('插件创建、追加、编辑和读取验证成功。'))throw new Error('读取的正文与写入内容不一致');
      setTestResult('创建、追加、编辑、读取均成功。\n测试文档：https://www.feishu.cn/docx/'+documentId+'\n你可以在飞书中删除这篇测试文档。');
    }catch(e){setTestResult((e as Error).message+(documentId?'\n已创建测试文档：https://www.feishu.cn/docx/'+documentId+'\n后续步骤未完成，请勿重复创建。':''));}finally{setBusy(false);}
  };
  const state=loading?'正在检查':connection?.requires_attention?'连接需要恢复':connection?.connected?'飞书已授权':connection?.configured?'等待飞书授权':'等待应用配置';
  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-white"><Link2 size={22}/></span><span className="text-lg font-semibold tracking-tight">飞书连接</span></div><span className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck size={17}/>个人私有 · 官方工具集</span></div></header>
    <div className="mx-auto max-w-5xl px-5 py-10 sm:px-8">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">把飞书带进对话</h1><p className="mt-3 max-w-xl text-base leading-7 text-muted-foreground">在 ChatGPT 和 Codex 中按需调用飞书官方工具，覆盖文档读写、知识库、多维表格、日历、任务等。</p></div><Button variant="outline" onClick={load} disabled={loading||busy}><RefreshCw size={16} className={loading?'animate-spin':''}/>刷新状态</Button></div>
      {message&&<div role="status" className="mb-6 rounded-xl border border-blue-200 bg-blue-50 px-5 py-4 text-sm leading-6 text-blue-950">{message}</div>}
      <section className="mb-6 flex flex-wrap items-center justify-between gap-5 rounded-2xl bg-[#12254b] px-6 py-6 text-white"><div><p className="text-sm text-blue-200">当前连接</p><h2 className="mt-1 text-xl font-semibold">{state}</h2><p className="mt-2 text-sm text-blue-100">{connection?.requires_attention?connection.connection_issue:connection?.connected?(connection.feishu_name?'已绑定：'+connection.feishu_name:'可以开始验证文档访问。'):'完成应用配置和一次授权后，即可从插件访问。'}</p></div>{needsLogin?<Button asChild className="bg-white text-[#12254b] hover:bg-blue-50"><a href="/signin-with-chatgpt?return_to=%2F">登录 ChatGPT</a></Button>:<Button onClick={connect} disabled={!connection?.configured||busy} className="bg-white text-[#12254b] hover:bg-blue-50">{busy?'处理中…':connection?.connected?'重新授权':'授权飞书'}</Button>}</section>
      <div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
        <section className="rounded-2xl border border-border bg-card p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="step-label">01 / 应用配置</p><h2 className="mt-2 text-xl font-semibold">连接你的飞书应用</h2></div>{connection?.configured&&!edit&&<div className="flex gap-2"><Button variant="ghost" size="sm" onClick={()=>setEdit(true)}>更换应用</Button><Button variant="ghost" size="sm" disabled={busy} onClick={removeConnection}>清除连接</Button></div>}</div>
          <p className="mt-3 text-sm leading-6 text-muted-foreground">在<a className="text-primary underline underline-offset-4" href="https://open.feishu.cn/app" target="_blank" rel="noreferrer">飞书开放平台</a>创建企业自建应用。凭据仅用于此连接，并加密保存在你的私有服务中。</p>
          {(!connection?.configured||edit)?<form onSubmit={save} className="mt-6 space-y-4"><div className="space-y-2"><Label htmlFor="app-id">App ID</Label><Input id="app-id" value={appId} onChange={e=>setAppId(e.target.value)} placeholder="cli_…" autoComplete="off" required disabled={needsLogin||busy}/></div><div className="space-y-2"><Label htmlFor="app-secret">App Secret</Label><Input id="app-secret" type="password" value={appSecret} onChange={e=>setAppSecret(e.target.value)} placeholder="填写飞书应用密钥" autoComplete="new-password" required disabled={needsLogin||busy}/><p className="text-sm text-muted-foreground">保存后不会再次显示密钥。</p></div><Button type="submit" className="w-full" disabled={needsLogin||busy||!appId||!appSecret}>{busy?'正在保存…':'保存应用凭据'}</Button></form>:<div className="mt-6 rounded-xl border border-border bg-muted/40 p-4"><p className="flex items-center gap-2 text-sm font-medium"><Check size={16} className="text-primary"/>应用凭据已保存</p><p className="mt-2 break-all font-mono text-sm text-muted-foreground">{connection.app_id}</p></div>}
          <div className="mt-6 border-t border-border pt-5"><h3 className="text-sm font-semibold">在飞书应用中添加重定向 URL</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">进入「安全设置 → 重定向 URL」，添加下面的完整地址，然后发布应用版本。</p><div className="mt-3 flex items-start gap-2 rounded-lg bg-muted p-3"><code className="min-w-0 flex-1 break-all text-sm leading-6">{connection?.callback_url||'登录后显示回调地址'}</code><Button type="button" variant="ghost" size="icon-sm" aria-label="复制回调地址" disabled={!connection?.callback_url} onClick={()=>copy(connection!.callback_url,'callback')}>{copied==='callback'?<Check/>:<Copy/>}</Button></div></div>
        </section>
        <div className="space-y-6"><section className="rounded-2xl border border-border bg-card p-6 sm:p-7"><p className="step-label">02 / 用户权限</p><h2 className="mt-2 text-xl font-semibold">检查应用授权范围</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">下列为文档和多维表格记录读取权限。其他工具还需对应的用户身份权限；若返回权限不足，在飞书后台开通并重新授权。现有历史授权也可能已包含这些权限。</p><div className="mt-5 space-y-3">{(['documents_write','bitable_write'] as AuthorizationProfile[]).map(profile=><label key={profile} className="flex items-start gap-3 rounded-lg border border-border p-3 text-sm"><input type="checkbox" checked={profiles.includes(profile)} disabled={busy} onChange={e=>setProfiles(p=>e.target.checked?[...p,profile]:p.filter(x=>x!==profile))}/><span>{connection?.authorization_profiles?.[profile]?.label||(profile==='documents_write'?'文档和知识库：创建与编辑':'多维表格任务：新增与更新记录')}</span></label>)}<Label htmlFor="extra-scopes">其他功能所需权限</Label><Input id="extra-scopes" value={extraScopes} disabled={busy} onChange={e=>setExtraScopes(e.target.value)} placeholder="填写飞书返回的权限名称，用空格分隔"/><p className="text-sm text-muted-foreground">选择后点击上方授权按钮，在飞书授权页核对新增权限。先在飞书应用后台开通对应权限。</p></div><div className="mt-5 space-y-2">{(connection?.authorization_request_scopes||defaultScopes).map(s=><div key={s} className="rounded-md bg-muted px-3 py-2 font-mono text-sm break-all">{s}</div>)}</div><Button variant="outline" className="mt-4" onClick={()=>copy((connection?.authorization_request_scopes||defaultScopes).join('\n'),'scopes')}>{copied==='scopes'?<Check size={16}/>:<Copy size={16}/>}复制权限列表</Button></section>
          <section className="rounded-2xl border border-border bg-card p-6"><p className="step-label">03 / 在对话中使用</p><p className="mt-3 text-sm leading-6 text-muted-foreground">安装个人插件后，在新的 ChatGPT 或 Codex 对话中选择「飞书连接」。授权保存后，先试一次文档搜索或读取。</p><div className="mt-4 space-y-3 text-sm"><p className="flex items-start gap-2"><FileSearch size={18} className="shrink-0 text-primary"/>“在飞书里搜索包含项目名称的文档。”</p><p className="flex items-start gap-2"><FileText size={18} className="shrink-0 text-primary"/>“读取这篇飞书文档并总结，附上来源链接。”</p></div><p className="mt-4 text-sm text-muted-foreground">已接入官方 OpenAPI MCP 0.5.1 的 501 个用户身份工具定义。先查找工具、检查参数，再执行。二进制上传下载暂不支持；并非所有工具都已获当前账号授权。</p></section>
        </div>
      </div>
      <section className="mt-6 rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-semibold">官方功能目录</h2><p className="mt-2 text-sm text-muted-foreground">搜索“知识空间”“多维表格”“日程”或“创建文档”，查看当前工具集覆盖的功能。</p><div className="mt-4 flex gap-2"><Input aria-label="功能关键词" value={toolQuery} onChange={e=>setToolQuery(e.target.value)} placeholder="例如：知识空间"/><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'feishu_find_tools',arguments:{query:toolQuery,limit:20}}})});const d=await r.json() as {result?:{structuredContent?:{total:number;tools:{name:string;description:string}[]}}};const c=d.result?.structuredContent;setToolResult(c?'匹配 '+c.total+' 个工具\n\n'+c.tools.map(t=>t.description+'\n'+t.name).join('\n\n'):'查询失败，请检查登录状态。');}catch{setToolResult('暂时无法加载功能目录。');}finally{setBusy(false);}}}>查找功能</Button></div>{toolResult&&<pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap text-sm leading-6">{toolResult}</pre>}</section>
      <section className="mt-6 rounded-2xl border border-border bg-card p-6 sm:p-7"><div className="mb-5"><h2 className="text-xl font-semibold">验证连接</h2><p className="mt-2 text-sm text-muted-foreground">授权后，用一个关键词或你有权访问的文档链接测试实际读取。</p></div><div className="mb-5 flex flex-wrap gap-3"><Button variant="outline" disabled={!connection?.connected||busy} onClick={()=>test('feishu_call_read_tool',{name:'feishu.library.list',arguments:{params:{page_size:30}}})}>列出我的文档库</Button><Button variant="outline" disabled={!connection?.connected||busy} onClick={()=>test('feishu_call_read_tool',{name:'wiki.v2.space.list',arguments:{params:{page_size:10}}})}>列出知识空间</Button><Button variant="outline" disabled={!connection?.connected||busy} onClick={verifyWrite}>验证文档写入（新建测试文档）</Button></div><div className="grid gap-5 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="search">文档关键词</Label><div className="flex gap-2"><Input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入文档标题关键词"/><Button disabled={!connection?.connected||busy||!query.trim()} onClick={()=>test('feishu_search_documents',{query,limit:5})}>搜索</Button></div></div><div className="space-y-2"><Label htmlFor="document">飞书文档链接</Label><div className="flex gap-2"><Input id="document" value={reference} onChange={e=>setReference(e.target.value)} placeholder="https://…feishu.cn/docx/…"/><Button disabled={!connection?.connected||busy||!reference.trim()} onClick={()=>test('feishu_read_document',{reference,max_chars:1000})}>读取</Button></div></div></div>{testResult&&<pre className="mt-5 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-muted p-4 text-sm leading-6">{testResult}</pre>}</section>
    </div><footer className="mx-auto max-w-5xl px-5 pb-8 text-sm text-muted-foreground sm:px-8">通过用户授权访问。读写能力以飞书账号权限为准；写操作仅在你明确要求时执行。</footer>
  </main>;
}
